spiderJson = {"nodes":[
{"weight":1,"rank":0.0, "id":1, "url":"https://felconet.com"},
{"weight":5,"rank":19.0, "id":2, "url":"https://felconet.com/about-bees.html"},
{"weight":5,"rank":19.0, "id":3, "url":"https://felconet.com/bee-keeping-farm.html"},
{"weight":5,"rank":19.0, "id":4, "url":"https://felconet.com/protective-clothing.html"},
{"weight":5,"rank":19.0, "id":5, "url":"https://felconet.com/index.html"}],
"links":[
{"source":0,"target":0,"value":3},
{"source":0,"target":1,"value":3},
{"source":0,"target":2,"value":3},
{"source":0,"target":3,"value":3},
{"source":0,"target":4,"value":3},
{"source":1,"target":1,"value":3},
{"source":1,"target":2,"value":3},
{"source":1,"target":3,"value":3},
{"source":1,"target":4,"value":3},
{"source":2,"target":1,"value":3},
{"source":2,"target":2,"value":3},
{"source":2,"target":3,"value":3},
{"source":2,"target":4,"value":3},
{"source":3,"target":1,"value":3},
{"source":3,"target":2,"value":3},
{"source":3,"target":3,"value":3},
{"source":3,"target":4,"value":3},
{"source":4,"target":1,"value":3},
{"source":4,"target":2,"value":3},
{"source":4,"target":3,"value":3},
{"source":4,"target":4,"value":3}]};